### ISSUE TITLE
nb_layers should be int

### ISSUE THREAD

**Issue by Hvitgar** [uoguelph-mlrg/Cutout#9]
When executing ` python train.py --dataset svhn --model wideresnet --learning_rate 0.01 --epochs 160 --cutout --length 20` I get the following error:

```
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    dropRate=0.4)
  File "Cutout/model/wide_resnet.py", line 58, in __init__
    self.block1 = NetworkBlock(n, nChannels[0], nChannels[1], block, 1, dropRate)
  File "Cutout/model/wide_resnet.py", line 38, in __init__
    self.layer = self._make_layer(block, in_planes, out_planes, nb_layers, stride, dropRate)
  File "Cutout/model/wide_resnet.py", line 41, in _make_layer
    for i in range(nb_layers):
TypeError: 'float' object cannot be interpreted as an integer
```

This error stems from the division [here](https://github.com/uoguelph-mlrg/Cutout/blob/dc0ddd6ec0a38cf00aeeb314681b1a612e836064/model/wide_resnet.py#L52). For Python3.x, integer division must be forced like this: `n = (depth - 4) // 6`

**Comment by MotiBaadror** [comment]
changing below line would remove the error
 ```for i in range(nb_layers):    ==> for i in range(int(nb_layers)):```
